{% set version = datetime.datetime.utcnow().strftime('0.%Y.%m.%d.%H.%M') %}

package:
  name: svmtk
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: CMAKE_DOWNLOAD_CGAL=OFF CMAKE_DOWNLOAD_PYBIND11=OFF CMAKE_BUILD_TESTING=OFF $PYTHON -m pip install -vv --ignore-installed --no-deps .

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
  host:
    # boost-cpp pin neede for cgal pin
    #- boost-cpp=1.85
    - libboost-devel
    - cgal-cpp=6.0.1
    - eigen
    - gmp
    - mpfr
    - setuptools
    - pybind11=2.13.5
    - python
    - pip
  run:
    - gmp
    - mpfr
    - numpy
    - python

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - SVMTK

  commands:
    - pytest -v tests
