#!/bin/bash


usage="$(basename "$0") converts binary surface file ${0%.*} to stl format. The converted file 
is stored in the folder <mesh> in the subject directory
where:
    -h  show this help text
    --proc
  
"

while getopts ':hs:' option; do
  case "$option" in
    h) echo "$usage"
       exit
    proc) echo "heyo"
       exit
  esac
done

mkdir -p ../mesh
ME=$(basename $0)
case $ME in
        lh.pial.extraction+mesh)
           ./lh.pial.extraction 
           ;;
        rh.pial.extraction+mesh)
           ./rh.pial.extraction  
           ;;
        lh.white.extraction+mesh)
           ./lh.white.extraction 
           ;;
        rh.white.extraction+mesh)
           ./rh.white.extraction  
           ;;
        full.extraction+mesh)
           ./lh.pial.extraction 
           ./lh.pial.extraction 
           ./lh.pial.extraction 
           ./lh.pial.extraction 
           ;;

esac
