#!/usr/bin/python

if __name__ =='__main__':
        import brainmesh as bm
        import argparse
        import os
        hemi , surface = os.path.basename(__file__).split(".")[0:2]
        parser = argparse.ArgumentParser(description='The smoothing of a {}-{}-proc.stl using Laplacian or volume preserving Laplacian'.format(hemi,surface) )

        parser.add_argument("--mdisp"  ,type=float , default= 0.8 ,help = "The maximum displacment of a point after smoothing. If not providedm ")
        parser.add_argument("--volume" ,action='store_true',help = "Include to use volume preserving Laplacian smoothing, known as taubian smoothing")
        Z = parser.parse_args() 

        surf  = bm.BrainSurface("../mesh/"+hemi+"-"+surface+"-proc.stl")

        if Z.volume : 
             surf.smooth_laplacian(Z.mdisp)
        else : 
             surf.smooth_taubian()


        surf.save("../mesh/"+hemi+"-"+surface+"-proc.stl") # make wrtier





