# Package for pushing conda packages to anaconda server
on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - conda-recipes/**
      - .github/workflows/build-conda-packages.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
      #  uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda-recipe/environment.yml
          environment-name: root

      - name: Build packages
        run: |
          conda mambabuild conda-recipe/
        env:
          CONDA_PY: ${{ matrix.py_version }}


      - uses: actions/upload-artifact@v4
        with:
          name: conda-build-{{ matrix.py_version }}
          path: "/home/runner/micromamba-root/envs/root/conda-bld/linux-64/*"
          if-no-files-found: error

      - name: Upload to Anaconda
        env:
          BINSTAR_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          if [[ ! -z "${BINSTAR_TOKEN}" ]]; then
            anaconda -t ${BINSTAR_TOKEN} upload ${CONDA_PREFIX}/conda-bld/linux-64/*.tar.bz2
          fi
