# Package for pushing conda packages to anaconda server
on:
  push:
    branches:
      - "master"
defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda-recipe/environment.yml
          environment-name: root
          extra-specs: |
            python=${{ matrix.py_version }}

      - name: Build packages
        run: |
          cp ${CONDA_PREFIX}/conda_build_config.yaml .
          conda mambabuild conda-recipe/


      - uses: actions/upload-artifact@v3
        with:
          name: conda-build-{{ matrix.py_version }}
          path: "/home/runner/micromamba-root/envs/root/conda-bld/linux-64/*"
          if-no-files-found: error

      - name: Upload to Anaconda
        env:
          BINSTAR_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run:
          anaconda -t ${BINSTAR_TOKEN} upload ${CONDA_PREFIX}/conda-bld/linux-64/*.tar.bz2
