name: Test building SVMTK

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macOS-latest]
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }} example

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Eigen3, mpfr, boost (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
           sudo apt-get update 
           sudo apt-get install -y libeigen3-dev libmpfr-dev libboost-dev cmake

    # - name: Install Eigen3, boost gmp (macos)
    #   if: matrix.os == 'macOS-latest'
    #   run: |
    #     brew install eigen boost


    - name: Install SVMTK
      run:
        python3 -m pip install -v .[test]
      env:
        CMAKE_BUILD_TESTING: "ON"

    - name: Run Tests
      run: pytest -v tests
